### ISSUE TITLE
mvp

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/transpilify#1]
@mmckegg we talked about making this module, so i made a repo here, we can implement it or not as we want.

the basic idea is to use `require.extensions` to transpile modules on `require` with browserify transforms.

notes:
- `require.extensions` [docs](https://iojs.org/api/globals.html#globals_require_extensions), [code](https://github.com/nodejs/io.js/blob/master/lib/module.js#L443).
- browserify transform [docs](https://github.com/substack/browserify-handbook#transforms).

an open question is what the API should be, considering that `require.extensions` expects file extensions, whereas browserify transforms handle every file. a simple proposal:

```
require('transpilify')({
  '.js': [
    'evalify'
  ]
})
```

then have analogous settings in the `package.json`, so you can run `require('transpilify')()` to default using those settings.

thoughts on this?

**Comment by mmckegg** [comment]
That option looks okay.

Another (crazy) idea:

``` js
var module = transquire('module-name', {
  transforms: ['brfs', 'evalify']
})
```

Avoids globals :wine_glass:

**Comment by ahdinosaur** [comment]
after some thought, keen. :smile: 

although it should be compatible with `browserify` so an open question is how can we make this work when browserified?

**Comment by ahdinosaur** [comment]
> how can we make this work when browserified?

ah, should be easy, as [according the browserify transform docs](https://github.com/substack/node-browserify#btransformtr-opts),

> Transform source code before parsing it for require() calls with the transform function or module name tr.

so that's as easy as

``` js
var transquirify = require('replacestream')('transquire(', 'require(')
```

another thing to mention is it'd be great if `transquire` used a cachefile like [browserify-incremental](https://www.npmjs.com/package/browserify-incremental) and [babel](http://babeljs.io/docs/usage/require/).

**Comment by ahdinosaur** [comment]
see simple transpiler in https://gist.github.com/mattdesl/aaf759da84cc44c22305

**Comment by ahdinosaur** [comment]
implemented [simple transpiler mvp](https://github.com/livejs/transpilify/commit/c992008d3077735a4fbfceb99eab03d2b8a07585), continuing with #2.
